MtoMRelationship/MtoMRelationship/Models/ErrorViewModel.cs
using System;

namespace MtoMRelationship.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MtoMRelationship/MtoMRelationship/ViewModels/ClassBatchEditViewModel.cs
using MtoMRelationship.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MtoMRelationship.ViewModels
{
    public class ClassBatchEditViewModel
    {

        public string ClassName { get; set; }

        public string ClassCode { get; set; }

        public ICollection<User> Managers { get; set; }

        public ICollection<string> SelectTrainerIds { get; set; }

        public ICollection<string> SelectManagerIds { get; set; }
    }
}

MtoMRelationship/MtoMRelationship/Controllers/ClassBatchesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MtoMRelationship.Data;
using MtoMRelationship.ViewModels;

namespace MtoMRelationship.Controllers
{
    public class ClassBatchesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ClassBatchesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: ClassBatches
        public async Task<IActionResult> Index()
        {
            return View(await _context.ClassBatches.ToListAsync());
        }

        // GET: ClassBatches/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var classBatch = await _context.ClassBatches
                .FirstOrDefaultAsync(m => m.Id == id);
            if (classBatch == null)
            {
                return NotFound();
            }

            return View(classBatch);
        }

        // GET: ClassBatches/Create
        public IActionResult Create()
        {
            ClassBatchEditViewModel classBatchEditViewModel = new ClassBatchEditViewModel
            {
                Managers = _context.Users.ToList(),
                SelectManagerIds = new List<string>()
            };
            return View(classBatchEditViewModel);
        }

        // POST: ClassBatches/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ClassBatchEditViewModel classBatchEditViewModel)
        {
            if (ModelState.IsValid)
            {
                var classBatch = new ClassBatch();

                var id = Guid.NewGuid().ToString();
                classBatch.Id = id;

                classBatch.ClassCode = classBatchEditViewModel.ClassCode;
                classBatch.ClassName = classBatchEditViewModel.ClassName;
                var userClassBatches = new List<UserClassBatch>();

                foreach (var item in classBatchEditViewModel.SelectManagerIds)
                {
                    var userClassBatch = new UserClassBatch()
                    {
                        ClassBatchId = id,
                        UserId = item
                    };
                    userClassBatches.Add(userClassBatch);
                }

                classBatch.Managers = userClassBatches;

                _context.ClassBatches.Add(classBatch);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(classBatchEditViewModel);
        }

        // GET: ClassBatches/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var classBatch = await _context.ClassBatches.FindAsync(id);
            if (classBatch == null)
            {
                return NotFound();
            }
            return View(classBatch);
        }

        // POST: ClassBatches/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Id,ClassName,ClassCode")] ClassBatch classBatch)
        {
            if (id != classBatch.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(classBatch);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClassBatchExists(classBatch.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(classBatch);
        }

        // GET: ClassBatches/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var classBatch = await _context.ClassBatches
                .FirstOrDefaultAsync(m => m.Id == id);
            if (classBatch == null)
            {
                return NotFound();
            }

            return View(classBatch);
        }

        // POST: ClassBatches/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var classBatch = await _context.ClassBatches.FindAsync(id);
            _context.ClassBatches.Remove(classBatch);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ClassBatchExists(string id)
        {
            return _context.ClassBatches.Any(e => e.Id == id);
        }
    }
}

MtoMRelationship/MtoMRelationship/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MtoMRelationship.Models;

namespace MtoMRelationship.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }


    }
}

MtoMRelationship/MtoMRelationship/Views/ClassBatches/Create.cshtml
@model ClassBatchEditViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>ClassBatch</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ClassName" class="control-label"></label>
                <input asp-for="ClassName" class="form-control" />
                <span asp-validation-for="ClassName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ClassCode" class="control-label"></label>
                <input asp-for="ClassCode" class="form-control" />
                <span asp-validation-for="ClassCode" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Managers" class="control-label"></label>
                <select class="js-example-basic-single" multiple="multiple" asp-for="SelectManagerIds"
                        asp-items="@(new SelectList(Model.Managers,"Id","UserName"))">
                    <option>Please select one</option>
                </select>
                <span asp-validation-for="ClassCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Trainers</label>
                <select class="js-example-basic-single" multiple="multiple" asp-for="SelectTrainerIds"
                        asp-items="@(new SelectList(Model.Managers,"Id","UserName"))">
                    <option>Please select one</option>
                </select>
                <span asp-validation-for="ClassCode" class="text-danger"></span>
            </div>


            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script>
        $(document).ready(function () {
            $('.js-example-basic-single').select2();
        });
    </script>
}

MtoMRelationship/MtoMRelationship/Views/ClassBatches/Delete.cshtml
@model MtoMRelationship.Data.ClassBatch

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ClassBatch</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ClassName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ClassName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ClassCode)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ClassCode)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MtoMRelationship/MtoMRelationship/Views/ClassBatches/Details.cshtml
@model MtoMRelationship.Data.ClassBatch

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>ClassBatch</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ClassName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ClassName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ClassCode)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ClassCode)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

MtoMRelationship/MtoMRelationship/Views/ClassBatches/Edit.cshtml
@model MtoMRelationship.Data.ClassBatch

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>ClassBatch</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="ClassName" class="control-label"></label>
                <input asp-for="ClassName" class="form-control" />
                <span asp-validation-for="ClassName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ClassCode" class="control-label"></label>
                <input asp-for="ClassCode" class="form-control" />
                <span asp-validation-for="ClassCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MtoMRelationship/MtoMRelationship/Views/ClassBatches/Index.cshtml
@model IEnumerable<MtoMRelationship.Data.ClassBatch>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ClassName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ClassCode)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ClassName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ClassCode)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

MtoMRelationship/MtoMRelationship/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<h1>Multiple Select Option</h1>

<select class="js-example-basic-single" name="state" multiple="multiple">
    <option value="HN">Ha Noi</option>
    <option value="HCM">Ho Chi Minh</option>
    <option value="DN">Da Nang</option>
    <option value="CT">Can Tho</option>
    <option value="NT">Nha Trang</option>
</select>

@*In your Javascript (external .js resource or <script> tag)*@

@section Scripts{ 
    <script>
        $(document).ready(function () {
            $('.js-example-basic-single').select2();
        });
    </script>
}

MtoMRelationship/MtoMRelationship/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MtoMRelationship</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MtoMRelationship</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ClassBatches" asp-action="Index">Class Management</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - MtoMRelationship - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>